### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by ibrahim-601** [faruk-ahmad/ml-proj-init#1]
If parameter project name is not given while creating a project structure, then instead of raising argument required error it raises type error.

OS: Windows 10
Python version: 3.7.7
ml-proj-init build: 1.0.2
Error message:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\prac\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\prac\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\prac\Scripts\ml-proj-init.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\prac\lib\site-packages\ml_proj_init\__main__.py", line 152, in start
    if val.is_valid_project_name(proj_name):
  File "c:\programdata\anaconda3\envs\prac\lib\site-packages\ml_proj_init\validation.py", line 38, in is_valid_project_name
    first_char = proj_name[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by faruk-ahmad** [comment]
@iriad11 Thank you for pointing out the issue. It was validation issue for the project name in case of None type. I hope it is fixed now. You can try the latest version from pypi using
```bash
pip install ml-proj-init==1.0.3
```
Let me know if the issue is fixed or not. Thanks again.

**Comment by ibrahim-601** [comment]
The issue is fixed. Thanks and welcome.
